### ISSUE TITLE
NDPDevOps - GitHub Issue Tracking Template

### ISSUE THREAD

**Issue by Consult2016** [Consult2016/ndp-devops#2]
**Description**

For a problem, summarize the problem in terms of what hardware/software the problem was detected in and the immediate symptoms (not the downstream/user impacts)

The <hardware/software/component> on <TAP/ITAP> <host/vm/etc> is/not <function/symptom>

This is a <single occurrence/sustained/intermittent> problem
The <host:/path/file.log> log show <log content>

other things describing the technical problem (not the solution or user impacts)
For a feature, summarize the need and indicate what components/software are involved.

Try to write this as a user story:

As <role/vendor>, I need <capability/feature incl. component> in order to <job function/requirement> by <date>.  

This need was derived from <Lab Access Request XYZ/email reference/meeting reference/etc> on <date>

**Lab Impact**

List impacts as bullets (as many as needed), please keep impacts to role/vendor (do not put hardware/software as a "role" that should be in the description)

<Role/Vendor> is unable to <job function/requirement>, causing <schedule/cost impact>

<Role/Vendor> will be unable to <job function/requirement/event> if not resolved by <date>

**Estimated Effort**

Identify who (by role or name) and approximate effort (hours/days), repeat as needed. Keep the "what" part very short, or just omit it.  Include procurement

<Role/Name> for <#/unknown> <hours/days>
<Role/Name> for <#/unknown> <hours/days>, to <TBS/investigate further>
<$x/TBD cost> for <qty> <hardware/software>

**Recommendations**

List technical and schedule recommendation as bullets, start with any pre-requisites/blockers. Include impacts of resolution. 
For bigger things, this should essentially be a list of sub-tasks to create in JIRA for this story/feature.

[blocker] Complete <task/ticket>

Mitigate problem by <move VM/something/etc> on <hardware/software/component> on <ITAP/TAP> <host/vm/etc>
<something> on <hardware/software/component> on <ITAP/TAP> <host/vm/etc>
Recommend resolving <ASAP/off-hours/next maint window>, will cause <outage description/user impact>

If no solution is know, then recommendation should discuss steps to determine solution.

Remove/replace <component> to <eliminate/isolate/test/check>

Mitigate problem by <move VM/something/etc> on <hardware/software/component> on <ITAP/TAP> <host/vm/etc>

Troubleshoot <component> by <something>

**Comment by morleys** [comment]
Added to Wiki.
